### ISSUE TITLE
Issue with SD card

### ISSUE THREAD

**Issue by SenyxLois** [mytja/treble_evo#17] opened 2024-09-10 15:53 UTC
![Screenshot_20240910-233538_Settings](https://github.com/user-attachments/assets/10200627-12ef-4d23-b598-154c476e342a)

It seem that EvoX can't read the exFat format on external storage(?)

I've tried PE (ponces) - Work without issue
I've tried EvoX (ponces) - Same SD problem
I've tried Lineage - Work without issue
And EvoX (mytja) - SD error

Is this a common problem for EvoX or something else? And no formating doesn't do anything. It's just format the SD card back to exFat and continue with the same error. Will reply later with logcat included

**Comment by mytja** [comment] 2024-09-10 23:01
Uhh, I can't reproduce it even with freshly exFAT formatted SD card. Logcat would certainly be useful.

**Comment by SenyxLois** [comment] 2024-09-11 00:50
Here's the logcat upon inserting the sd card

```
09-11 07:51:48.895   668  3564 D vold    : /dev/block/vold/public:179,1: LABEL="android" UUID="FEF4-B3D4" TYPE="exfat"
09-11 07:51:48.897   668  3564 E vold    : public:179,1 unsupported filesystem exfat
09-11 07:51:48.899  1969  2370 E StorageManagerService: android.os.ServiceSpecificException:  (code -5)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.Parcel.createException(Parcel.java:3041)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.Parcel.readException(Parcel.java:3024)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.Parcel.readException(Parcel.java:2966)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.IVold$Stub$Proxy.mount(IVold.java:1642)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at com.android.server.StorageManagerService.mount(StorageManagerService.java:2265)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at com.android.server.StorageManagerService.-$$Nest$mmount(StorageManagerService.java:0)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at com.android.server.StorageManagerService$StorageManagerServiceHandler.handleMessage(StorageManagerService.java:748)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.Looper.loopOnce(Looper.java:205)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.Looper.loop(Looper.java:294)
09-11 07:51:48.899  1969  2370 E StorageManagerService: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-11 07:51:48.900  1969  2370 I StorageSessionController: Notifying volume state changed for session with id: public:179,1
09-11 07:51:48.901  1969  2370 I StorageUserConnection: No session found for sessionId: public:179,1
09-11 07:51:48.852     0     0 I         : [0:SettingsProvide: 2341] Send signal 11 from SettingsProvide(2341) to SettingsProvide(2341) : 1
09-11 07:51:48.903  2572  2572 D StorageNotification: Notifying about public volume: VolumeInfo{public:179,1}:
09-11 07:51:48.903  2572  2572 D StorageNotification:     type=PUBLIC diskId=disk:179,0 partGuid= mountFlags=VISIBLE_FOR_WRITE 
09-11 07:51:48.903  2572  2572 D StorageNotification:     mountUserId=0 state=UNMOUNTED 
09-11 07:51:48.903  2572  2572 D StorageNotification:     fsType=null fsUuid=null fsLabel=null 
09-11 07:51:48.903  2572  2572 D StorageNotification:     path=null internalPath=null 
09-11 07:51:48.905  1969  2370 I StorageSessionController: Notifying volume state changed for session with id: public:179,1
09-11 07:51:48.906  1969  2370 I StorageUserConnection: No session found for sessionId: public:179,1
09-11 07:51:48.906  4451  4451 D ExternalStorage: After updating volumes, found 1 active roots
09-11 07:51:48.858     0     0 I         : [2:   FileObserver: 2019] Send signal 11 from FileObserver(2019) to FileObserver(2019) : 1
09-11 07:51:48.908  2572  2572 D StorageNotification: Notifying about public volume: VolumeInfo{public:179,1}:
09-11 07:51:48.908  2572  2572 D StorageNotification:     type=PUBLIC diskId=disk:179,0 partGuid= mountFlags=VISIBLE_FOR_WRITE 
09-11 07:51:48.908  2572  2572 D StorageNotification:     mountUserId=0 state=CHECKING 
09-11 07:51:48.908  2572  2572 D StorageNotification:     fsType=null fsUuid=null fsLabel=null 
09-11 07:51:48.908  2572  2572 D StorageNotification:     path=null internalPath=null 
09-11 07:51:48.911  1969  2370 I StorageSessionController: Notifying volume state changed for session with id: public:179,1
09-11 07:51:48.912  1969  2370 I StorageUserConnection: No session found for sessionId: public:179,1
09-11 07:51:48.912  4451  4451 D ExternalStorage: After updating volumes, found 1 active roots
09-11 07:51:48.913  3592  3592 V MediaStore: Examining volume emulated;0 with name external_primary and state mounted
09-11 07:51:48.914  3592  3592 V MediaStore: Examining volume public:179,1 with name fef4-b3d4 and state unmountable
09-11 07:51:48.915  2572  2572 D StorageNotification: Notifying about public volume: VolumeInfo{public:179,1}:
09-11 07:51:48.915  2572  2572 D StorageNotification:     type=PUBLIC diskId=disk:179,0 partGuid= mountFlags=VISIBLE_FOR_WRITE 
09-11 07:51:48.915  2572  2572 D StorageNotification:     mountUserId=0 state=UNMOUNTABLE 
09-11 07:51:48.915  2572  2572 D StorageNotification:     fsType=exfat fsUuid=FEF4-B3D4 fsLabel=android 
09-11 07:51:48.915  2572  2572 D StorageNotification:     path=null internalPath=null 
09-11 07:51:48.915  4451  4451 D ExternalStorage: After updating volumes, found 1 active roots
09-11 07:51:48.917  1969  2370 D StorageManagerService: Volume public:179,1 broadcasting checking to UserHandle{0}
09-11 07:51:48.922  1969  2370 D StorageManagerService: Volume public:179,1 broadcasting unmountable to UserHandle{0}
09-11 07:51:48.923  4451  4451 D ExternalStorage: After updating volumes, found 1 active roots
09-11 07:51:48.924  3592  3592 V MediaStore: Examining volume emulated;0 with name external_primary and state mounted
09-11 07:51:48.924  3592  3592 V MediaStore: Examining volume public:179,1 with name fef4-b3d4 and state unmountable
09-11 07:51:48.926  4451  4451 D ExternalStorage: After updating volumes, found 1 active roots
09-11 07:51:48.917     0     0 E         : I[0:      swapper/0:    0] Tx has been idle [BT]
09-11 07:51:48.918     0     0 E         : [0:    kworker/0:5: 2065] going to sleep... [BT]
09-11 07:51:48.918     0     0 E         : [0:    kworker/0:5: 2065] hsuart_power off [BT]
09-11 07:51:49.045     0     0 E         : I[2:      swapper/2:    0] netio w0 56 2 0 0 0 0
09-11 07:51:49.139  1969  1969 W NotificationHistory: Attempted to add notif for locked/gone/disabled user 0
09-11 07:51:49.192  2572  2725 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
09-11 07:51:49.203  3524  5399 I bauth_FPBAuthService: pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 7.0.0.0
09-11 07:51:49.203  3524  5399 I bauth_FPBAuthService: thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
09-11 07:51:49.203  3524  5399 I bauth_FPBAuthService: FPBAuthService, 11511
09-11 07:51:49.205  2572  2725 D LocalImageResolver: Couldn't use ImageDecoder for drawable, falling back to non-resized load.
09-11 07:51:49.155     0     0 E [0:    kworker/0:5: 2065] msm_pcie_drv_suspend: PCIe: RC2: prevnet_l1=0 LTSSM_STATE=:LTSSM_L1_IDLE
09-11 07:51:49.234     0     0 W         : I[3:dhd_rpm_state_t:  563] dhd_os_check_wakelock_all wakelock c-0 wl-0 wd-0 rx-1 ctl-0 intr-0 scan-0 evt-0, pm-0, txfl-0 nan-0
09-11 07:51:49.234     0     0 W [3:dhd_rpm_state_t:  563] dhd_runtimepm_state: bus is active with dhd_bus_busy_state = 0x0
09-11 07:51:49.343     0     0 E         : I[0:      swapper/0:    0] hostwake line change [BT]
09-11 07:51:49.343     0     0 E         : [0:    kworker/0:5: 2065] waking up... [BT]
09-11 07:51:49.344     0     0 E         : [0:    kworker/0:5: 2065] hsuart_power on [0] [BT]
09-11 07:51:49.416  1471  2679 I sensors-hal: handle_sns_client_event:541, [0][230] accel_sample [ 0.518,  0.515,  9.602] 21869721072636
09-11 07:51:49.443  2880  2888 W droid.bluetooth: Reducing the number of considered missed Gc histogram windows from 281 to 100
09-11 07:51:49.737     0     0 W I[3:dhd_rpm_state_t:  563] dhd_runtimepm_state: DHD Idle state!! -  idletime :5, wdtick :100, PS mode off dur: 0 sec
09-11 07:51:49.738     0     0 W I[3:dhd_rpm_state_t:  563] __dhd_txflowcontrol: Stop Netif Queue
09-11 07:51:49.738     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_bus_suspend: Entering suspend state
09-11 07:51:49.740     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_send_mb_data: send H2D_HOST_D3_INFORM to dongle
09-11 07:51:49.755     0     0 W I[0:      swapper/0:    0] D2H_MB_DATA: D3 ACK
09-11 07:51:49.755     0     0 W I[0:      swapper/0:    0] dhd_bus_handle_d3_ack: D3_ACK Recieved
09-11 07:51:49.755     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_bus_suspend: Got D3 Ack
09-11 07:51:49.755     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_dump_resource: BAR0(VA): 0x0000000000000000, BAR0(PA): 0x0000000060800000, SIZE: 32768
09-11 07:51:49.755     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_dump_resource: BAR1(VA): 0x0000000000000000, BAR1(PA): 0x0000000060400000, SIZE: 4194304
09-11 07:51:49.755     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_suspend_dev: Enter: TS(2409102351490803)
09-11 07:51:49.755     0     0 W I[0:      swapper/0:    0] dhdpci_bus_read_frames: Bus is in power save state (2). Skip processing rest of ring buffers.
09-11 07:51:49.756     0     0 W [3:dhd_rpm_state_t:  563] BEFORE_EP_SUSPEND: BaseAddress0(0x10)=0x60800004, BaseAddress1(0x18)=0x60400004 PCIE_CFG_PMCSR(0x4c)=0x4108 PCI_BAR1_WIN(0x84)=(0x0)
09-11 07:51:49.775     0     0 W [3:dhd_rpm_state_t:  563] AFTER_EP_SUSPEND: BaseAddress0(0x10)=0x60800004, BaseAddress1(0x18)=0x60400004 PCIE_CFG_PMCSR(0x4c)=0x410b PCI_BAR1_WIN(0x84)=(0x0)
09-11 07:51:49.777     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_pm_suspend: PCIe RC0: PARF LTSSM_STATE: LTSSM_L1_IDLE
09-11 07:51:49.778     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_pm_suspend: RC0: PME_TURNOFF_MSG is sent out
09-11 07:51:49.788     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_pm_suspend: PCIe RC0: PARF LTSSM_STATE: LTSSM_L2_IDLE
09-11 07:51:49.788     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_disable: PCIe: Assert the reset of endpoint of RC0.
09-11 07:51:49.789     0     0 W         : [3:dhd_rpm_state_t:  563] dhd_runtimepm_state, update suspend states
09-11 07:51:49.789     0     0 W I[3:dhd_rpm_state_t:  563] __dhd_txflowcontrol: Start Netif Queue
09-11 07:51:49.833     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_bus_suspend: Entering resume state
09-11 07:51:49.834     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_enable: PCIe: Assert the reset of endpoint of RC0.
09-11 07:51:49.838     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_enable: PCIe: RC0: PCIE20_PARF_INT_ALL_MASK: 0x7f80c202
09-11 07:51:49.840     0     0 E [3:dhd_rpm_state_t:  563] pcie_phy_init: RC0: number of PHY retries:1(Max:1, Total:1572).
09-11 07:51:49.840     0     0 I [3:dhd_rpm_state_t:  563] pcie_phy_init: PCIe RC0 PHY is ready!
09-11 07:51:49.850     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_enable: PCIe: Release the reset of endpoint of RC0.
09-11 07:51:49.857     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_link_train: PCIe RC0: LTSSM_STATE: LTSSM_DETECT_QUIET
09-11 07:51:49.862     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_link_train: PCIe RC0: LTSSM_STATE: LTSSM_DETECT_QUIET
09-11 07:51:49.867     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_link_train: PCIe RC0: LTSSM_STATE: LTSSM_L0
09-11 07:51:49.867     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_link_train: PCIe RC0 link initialized
09-11 07:51:49.868     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_enable: PCIe RC0 Max GEN3, EP GEN2
09-11 07:51:49.868     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_enable: PCIe RC0 Target GEN1, EP GEN1
09-11 07:51:49.868     0     0 I [3:dhd_rpm_state_t:  563] msm_pcie_enable: PCIe RC0 Current GEN1, 1 lanes
09-11 07:51:49.869     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_resume_dev: Enter: TS(2409102351490917)
09-11 07:51:49.872     0     0 W [3:dhd_rpm_state_t:  563] AFTER_EP_RESUME: BaseAddress0(0x10)=0x60800004, BaseAddress1(0x18)=0x60400004 PCIE_CFG_PMCSR(0x4c)=0xc108 PCI_BAR1_WIN(0x84)=(0x0)
09-11 07:51:49.873     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_dump_resource: BAR0(VA): 0x0000000000000000, BAR0(PA): 0x0000000060800000, SIZE: 32768
09-11 07:51:49.873     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_dump_resource: BAR1(VA): 0x0000000000000000, BAR1(PA): 0x0000000060400000, SIZE: 4194304
09-11 07:51:49.874     0     0 W [3:dhd_rpm_state_t:  563] dhd_bus_hostready: Read PCICMD Reg: 0x00100006
09-11 07:51:49.874     0     0 W [3:dhd_rpm_state_t:  563] dhd_bus_dump_dar_registers: dar_clk_ctrl(0xa08:0x1010040) dar_pwr_ctrl(0xa0c:0x30000) dar_intstat(0xa10:0x4000000)
09-11 07:51:49.874     0     0 W [3:dhd_rpm_state_t:  563] dhd_bus_dump_dar_registers: dar_errlog(0xa60:0x0) dar_erraddr(0xa64:0x0) dar_pcie_mbint(0xa68:0x0)
09-11 07:51:49.874     0     0 W [3:dhd_rpm_state_t:  563] dhd_bus_hostready: Ring Hostready:1575
09-11 07:51:49.874     0     0 W [3:dhd_rpm_state_t:  563] dhd_runtimepm_state: runtime resume ended
09-11 07:51:50.203  3524  5399 I bauth_FPBAuthService: pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 7.0.0.0
09-11 07:51:50.203  3524  5399 I bauth_FPBAuthService: thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
09-11 07:51:50.204  3524  5399 I bauth_FPBAuthService: FPBAuthService, 11511
09-11 07:51:50.201     0     0 E         : I[0:      swapper/0:    0] hostwake line change [BT]
09-11 07:51:50.201     0     0 E [0:    kworker/0:5: 2065] bluesleep_sleep_wakeup: already wake up, so start timer... [BT]
09-11 07:51:50.344     0     0 I         : [0: irq/417-sec_ts:  315] sec_ts 8-0048: [sec_input][P] tID:0.1799 z:26 major:6 minor:6 loc:C.S tc:1 type:0 noise:(0,00), nlvl:3, maxS:125, hid:0
09-11 07:51:50.345     0     0 D [1:  kworker/u17:5:29574] set_freq_limit: id(1) freq(1171200)
09-11 07:51:50.377     0     0 W I[3:dhd_rpm_state_t:  563] dhd_runtimepm_state: DHD Idle state!! -  idletime :5, wdtick :100, PS mode off dur: 0 sec
09-11 07:51:50.377     0     0 W I[3:dhd_rpm_state_t:  563] __dhd_txflowcontrol: Stop Netif Queue
09-11 07:51:50.377     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_bus_suspend: Entering suspend state
09-11 07:51:50.381     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_send_mb_data: send H2D_HOST_D3_INFORM to dongle
09-11 07:51:50.429  1969  1969 W binder:1969_6: type=1400 audit(0.0:1158479): avc:  denied  { getattr } for  scontext=u:r:system_server:s0 tcontext=u:r:platform_app:s0:c512,c768 tclass=process permissive=0
09-11 07:51:50.429  1969  1969 W binder:1969_6: type=1300 audit(0.0:1158479): arch=c00000b7 syscall=63 success=no exit=-13 a0=2e0 a1=7abcbe9a00 a2=fff a3=0 items=0 ppid=1754 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 exe="/system/bin/app_process64" subj=u:r:system_server:s0 key=(null)
09-11 07:51:50.429   664   664 W auditd  : type=1327 audit(0.0:1158479): proctitle="system_server"
09-11 07:51:50.429   664   664 W auditd  : type=1320 audit(0.0:1158479): 
09-11 07:51:50.433  1969  1969 W binder:1969_6: type=1400 audit(0.0:1158480): avc:  denied  { getattr } for  scontext=u:r:system_server:s0 tcontext=u:r:platform_app:s0:c512,c768 tclass=process permissive=0
09-11 07:51:50.386     0     0 W [1:  binder:1969_6: 2835] audit: audit_lost=4595238 audit_rate_limit=5 audit_backlog_limit=64
09-11 07:51:50.386     0     0 E [1:  binder:1969_6: 2835] audit: rate limit exceeded
09-11 07:51:50.440  2572  2572 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-11 07:51:50.440  2572  2572 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-11 07:51:50.394     0     0 W I[0:  binder:1969_6: 2835] D2H_MB_DATA: D3 ACK
09-11 07:51:50.394     0     0 W I[0:  binder:1969_6: 2835] dhd_bus_handle_d3_ack: D3_ACK Recieved
09-11 07:51:50.394     0     0 W I[0:  binder:1969_6: 2835] dhdpci_bus_read_frames: Bus is in power save state (2). Skip processing rest of ring buffers.
09-11 07:51:50.394     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_bus_suspend: Got D3 Ack
09-11 07:51:50.394     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_dump_resource: BAR0(VA): 0x0000000000000000, BAR0(PA): 0x0000000060800000, SIZE: 32768
09-11 07:51:50.394     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_dump_resource: BAR1(VA): 0x0000000000000000, BAR1(PA): 0x0000000060400000, SIZE: 4194304
09-11 07:51:50.394     0     0 W [3:dhd_rpm_state_t:  563] dhdpcie_suspend_dev: Enter: TS(2409102351500443)
09-11 07:51:50.396     0     0 W [3:dhd_rpm_state_t:  563] BEFORE_EP_SUSPEND: BaseAddress0(0x10)=0x60800004, BaseAddress1(0x18)=0x60400004 PCIE_CFG_PMCSR(0x4c)=0xc108 PCI_BAR1_WIN(0x84)=(0x0)
09-11 07:51:50.462  2572  2696 E OpenGLRenderer: Unable to match the desired swap behavior.
09-11 07:51:50.416     0     0 W [1:dhd_rpm_state_t:  563] AFTER_EP_SUSPEND: BaseAddress0(0x10)=0x60800004, BaseAddress1(0x18)=0x60400004 PCIE_CFG_PMCSR(0x4c)=0x410b PCI_BAR1_WIN(0x84)=(0x0)
09-11 07:51:50.419     0     0 I [1:dhd_rpm_state_t:  563] msm_pcie_pm_suspend: PCIe RC0: PARF LTSSM_STATE: LTSSM_L1_IDLE
09-11 07:51:50.419     0     0 I [1:dhd_rpm_state_t:  563] msm_pcie_pm_suspend: RC0: PME_TURNOFF_MSG is sent out
09-11 07:51:50.419     0     0 I [1:dhd_rpm_state_t:  563] msm_pcie_pm_suspend: PCIe RC0: PARF LTSSM_STATE: LTSSM_L2_IDLE
09-11 07:51:50.419     0     0 I [1:dhd_rpm_state_t:  563] msm_pcie_disable: PCIe: Assert the reset of endpoint of RC0.
09-11 07:51:50.421     0     0 W         : [1:dhd_rpm_state_t:  563] dhd_runtimepm_state, update suspend states
09-11 07:51:50.421     0     0 W I[1:dhd_rpm_state_t:  563] __dhd_txflowcontrol: Start Netif Queue
09-11 07:51:50.485  3284 30053 W ComplianceFilepathHandl: Tracing data is not available [CONTEXT service_id=357 ]
09-11 07:51:50.437     0     0 I         : [2:       Thread-3: 2351] Send signal 11 from Thread-3(2351) to Thread-3(2351) : 1
09-11 07:51:50.488  1530  1530 E SecVibrator-HAL2.2_A: performWrapper
09-11 07:51:50.488  1530  1530 E SecVibrator-HAL2.2_A: >>>>>>>>>> performEffect start effect : 2, strength : 1
09-11 07:51:50.488  1530  1530 E SecVibrator-HAL2.2_A: setPerformAmplitude : 1 change to 6700
09-11 07:51:50.488  1530  1530 E SecVibrator-HAL2.2_A: >>>>>>>>>> preparePerform start effect : 2, amplitude : 6700
09-11 07:51:50.488  1530  1530 E SecVibrator-HAL2.2_A: performEffect support : TICK
09-11 07:51:50.488  1530  1530 E SecVibrator-HAL2.2_A: sehPerformPrebakedHapticPattern pattern : 50, amplitude : 6700
09-11 07:51:50.488  1530  1530 E SecVibrator-HAL2.2_A: sehPerformPrebakedHapticPattern one shoot starts
09-11 07:51:50.488  1530  1530 E SecVibrator-HAL2.2_A: >> writeNode node:/timed_output/vibrator/intensity val:6700
09-11 07:51:50.489  2572  2725 I QuickAccessWalletTile: Successfully retrieved wallet cards.
09-11 07:51:50.489  2572  2725 D QuickAccessWalletTile: No wallet cards exist.
09-11 07:51:50.440     0     0 I         : [2:vibrator@2.2-se: 1530] [VIB] cs40l2x_intensity_store: 6700 (cp dig scale: 28)
09-11 07:51:50.490  1530  1530 E SecVibrator-HAL2.2_A: << writeNode node OK 5
09-11 07:51:50.490  1530  1530 E SecVibrator-HAL2.2_A: >> writeNode node:/timed_output/vibrator/cp_trigger_index val:50
09-11 07:51:50.490  1530  1530 E SecVibrator-HAL2.2_A: << writeNode node OK 3
09-11 07:51:50.490  1530  1530 E SecVibrator-HAL2.2_A: >> writeNode node:/timed_output/vibrator/enable val:1000
09-11 07:51:50.490  1530  1530 E SecVibrator-HAL2.2_A: << writeNode node OK 5
09-11 07:51:50.490  1530  1530 E SecVibrator-HAL2.2_A: sehPerformPrebakedHapticPattern one shoot end
09-11 07:51:50.490  1530  1530 E SecVibrator-HAL2.2_A: <<<<<<<<<< performEffect end effect : 2, strength : 1
09-11 07:51:50.442     0     0 I         : [0:vibrator@2.2-se: 1530] [VIB] cs40l2x_cp_trigger_index_store SEP index:50
09-11 07:51:50.442     0     0 I         : [0:vibrator@2.2-se: 1530] [VIB] cs40l2x_cp_trigger_index_store index:59 (num_waves:143)
09-11 07:51:50.442     0     0 I         : [0:vibrator@2.2-se: 1530] [VIB] cs40l2x_vibe_enable: 1000ms
09-11 07:51:50.442     0     0 I         : [3:  kworker/u17:5:29574] [FACTORY] ssc_motor_notify: Send Motor enable
09-11 07:51:50.442     0     0 I         : [3:  kworker/u17:5:29574] vib_notifier_notify done(0x0)
09-11 07:51:50.442     0     0 I         : [3:  kworker/u16:6:10363] [FACTORY] slpi_motor_work_func: msg_buf = 1
09-11 07:51:50.491  1567  1567 I SSC_DAEMON: physical_sensor_test_req_msg Sensor type :0, Msg type:3
09-11 07:51:50.495  1567  2171 I SSC_DAEMON: accel_motor_state_event: 1, 1
09-11 07:51:50.495  1471  2679 I sensors-hal: handle_sns_client_event:541, [0][240] accel_sample [ 0.460,  0.475,  9.625] 21871727970501
09-11 07:51:50.496  1567  2171 I SSC_DAEMON: LCE motor: 1
09-11 07:51:50.496  1567  2171 I SSC_DAEMON: SBOM motor: 1
09-11 07:51:50.453     0     0 I         : [2:irq/35-cs40l25a:  371] cs40l2x 9-0040: Entering cs40l2x_irq...
09-11 07:51:50.455     0     0 I         : [2:irq/35-cs40l25a:  371] [VIB] cs40l2x_irq: TRIG_STOP
09-11 07:51:50.456     0     0 I         : [3:irq/35-cs40l25a:  371] cs40l2x 9-0040: Exiting cs40l2x_irq after processing 1 event

```

**Comment by mytja** [comment] 2024-09-11 16:47
Your kernel seems to be reporting no native exFAT support (which was only added in Linux kernel 5.4). You can check which filesystems are supported using `cat /proc/filesystems`, ran as root user.

I'm also not sure why it works on Lineage, but not on Evolution. Both share the exact same vold (SD card manager).

**Comment by SenyxLois** [comment] 2024-09-12 13:16
Well Samsung (which is my device) implement native exFAT support on kernel level since mid 2010s. Maybe a problem with vendor configuration? since Im using a Japan device that has its own custom vendor file

**Comment by Vad1mCSO2** [comment] 2024-09-13 12:57
Works fine on FAT32 format only at http://ridgecrop.co.uk/index.htm?guiformat.htm [Click the software window to download]

**Comment by mytja** [comment] 2024-09-21 10:04
It seems as if more devices are affected. I've checked and all exFAT-related TrebleDroid's patches were applied correctly. As I don't have this issue, I'd appreciate somebody sending the contents of `/proc/filesystems` using the command `adb shell cat /proc/filesystems`. It might be that kernel isn't reporting the existence of exFAT, but sdFAT and TrebleDroid's patches don't affect that (or something similar?)

**Comment by Quanquan6169Vietnamese** [comment] 2024-09-23 07:50
The problem is that most roms currently have quite high capacity, above 4gb, vfat format is less than 4gb, exfat format is higher, but gsi rom does not support exfat,
![Screenshot_20240923-144416_Root Explorer](https://github.com/user-attachments/assets/0707dcb8-71ee-439c-9a23-7ec1f792aaa6)

**Comment by mytja** [comment] 2024-09-23 16:43
Okay, great. I've found the problem. I'll resolve it with the next beta release (towards the end of the week I hope). Thank you to all who participated.

**Comment by mytja** [comment] 2024-10-11 21:21
Should be fixed in latest version: https://github.com/mytja/treble_evo/releases/tag/20241011

Sorry for the delay, there were some busy weeks.

**Closed by mytja** 2024-10-11 21:21 UTC
Labels: bug

**Comment by mytja** [comment] 2024-10-11 22:24
Had to retract the build, because Superuser was included, despite having patches that explicitly remove it. That patch is problematic and doesn't want to apply automatically and I need to apply it manually, and I forgot to do that. This meant that no Play Integrity was present.

I am now building a new release that should finish building in about 2 hours, but it's likely I'll publish it in the morning.

**Comment by mytja** [comment] 2024-10-12 11:23
The actual new image, including the fix is up now: https://github.com/mytja/treble_evo/releases/tag/20241012

**Comment by SenyxLois** [comment] 2024-10-12 12:17
Currently downloading the image, will inform if it work :+1:
