### ISSUE TITLE
No Play Integrity

### ISSUE THREAD

**Issue by imbroglius** [mytja/treble_evo#8] opened 2024-09-06 07:51 UTC
Hi,
did you sign your latest build? Actually there is no play integrity.
![Screenshot_20240906-094745_Play Integrity API Checker](https://github.com/user-attachments/assets/1c094b18-68ce-4557-9d99-ad3346200e03)

**Comment by mitzamike** [comment] 2024-09-06 07:54
I'm on the latest slim build, Play Integrity is fine

![Screenshot_20240906-105302_Play Integrity API Checker](https://github.com/user-attachments/assets/5bb43e13-c012-41de-80e7-4cca8612403f)

**Comment by mitzamike** [comment] 2024-09-06 08:33
I did find something unusual that wasn't happening on the previous build though.

In the Key Attestation app, when ticking "Use app generated attest key" in the three-dot menu, it says "Certificate chain is not trusted". When not ticked it's fine, but it's pretty weird because this wasn't happening on the previous build.

This is on the latest slim build btw.

![Screenshot_20240906-112751_Key Attestation](https://github.com/user-attachments/assets/682b6969-677e-4e61-a66e-1e7843fc7b66)

**Comment by imbroglius** [comment] 2024-09-06 08:50
I did a dirty flash to update from 9.3 to 9.4

I will do a clean flash this evening and tell you what happens.

**Comment by mytja** [comment] 2024-09-06 08:57
> I did find something unusual that wasn't happening on the previous build though.
> 
> In the Key Attestation app, when ticking "Use app generated attest key" in the three-dot menu, it says "Certificate chain is not trusted". When not ticked it's fine, but it's pretty weird because this wasn't happening on the previous build.
> 
> This is on the latest slim build btw.
> 

This is intended behaviour. When you click the option Use app generated attest key, the app generates the certificate, which of course is not trusted.

Play Integrity passes on latest normal build for me, with both integrated PIF and PIF Magisk module. I'm not sure what is going wrong here.

Maybe I need to test a clean flash, but I think it works even on a clean flash.

**Comment by mytja** [comment] 2024-09-06 08:59
Although it's possible I forgot to sign some apps and I'm not really sure due to using beta fingerprint, which allows for test signed images. But in any case basic integrity should pass.

**Comment by mytja** [comment] 2024-09-06 09:19
No integrity is usually a sign that there is a su binary inside /system/xbin/su. The patching process sometimes for unknown reasons doesn't apply some patches. Would you please check if there exists /system/xbin/su?

**Comment by Marcos-Dtel** [comment] 2024-09-06 11:01
![Screenshot_20240905-193237_Key Attestation](https://github.com/user-attachments/assets/aee55413-1c2e-47a3-a903-39c08002a1bd)
![Screenshot_20240905-193303_Momo](https://github.com/user-attachments/assets/395ff403-6b93-4f41-85f2-af2081deca81)
This was yesterday, as soon as I installed the slim version

**Comment by Marcos-Dtel** [comment] 2024-09-06 11:06
Screenshots were from version 9.4 slim

**Comment by mitzamike** [comment] 2024-09-06 11:09
> ![Screenshot_20240905-193237_Key Attestation](https://private-user-images.githubusercontent.com/179177849/365140140-aee55413-1c2e-47a3-a903-39c08002a1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjA5MjgsIm5iZiI6MTcyNTYyMDYyOCwicGF0aCI6Ii8xNzkxNzc4NDkvMzY1MTQwMTQwLWFlZTU1NDEzLTFjMmUtNDdhMy1hOTAzLTM5YzA4MDAyYTFiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMTAzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDA5MWRmNDlhNWZlMmNjNjk0MjhkODA4Njg2YWVjMDViNzRlMTNkMGU4YTA4M2I3MDgzMDdkZTkwYTZkMmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CZU5BNJKwKLvwVgjs-oc4u3VDfliVjVPWWq2ozWTp9Y) ![Screenshot_20240905-193303_Momo](https://private-user-images.githubusercontent.com/179177849/365140194-395ff403-6b93-4f41-85f2-af2081deca81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjA5MjgsIm5iZiI6MTcyNTYyMDYyOCwicGF0aCI6Ii8xNzkxNzc4NDkvMzY1MTQwMTk0LTM5NWZmNDAzLTZiOTMtNGY0MS04NWYyLWFmMjA4MWRlY2E4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMTAzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzlhZmY2OWE4YjBiN2U5ZGJiYWExNzFmZTcxYTI5YTQ2ZWQ4ZTdjZGFjOTBlNTAxMTBhMzhhMWQzNjllNDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DaAtCd0359cGtGSG1GuCRFU-8HTS7liH_R1C-5VFL5E) This was yesterday, as soon as I installed the slim version


Momo looks normal.

As for Key Attestation, it should look like this (when "Use app generated attest key" is unticked)
I'm guessing you installed it from the Play Store which is not the good version. You should get it from Github.
![Screenshot_20240906-140441_Key Attestation](https://github.com/user-attachments/assets/0dc826b3-9dce-4a00-82fa-6191b550365d)

**Comment by Marcos-Dtel** [comment] 2024-09-06 12:19
I installed version from Github.

**Comment by mytja** [comment] 2024-09-06 13:30
Play Integrity passes even on clean latest test image slim install (through DSU).

<details>

![Screenshot_20240906-152807_Google Play Store](https://github.com/user-attachments/assets/64ea99fd-d31d-4748-84bb-8f0e7c8972ff)

</details>

**Comment by mytja** [comment] 2024-09-18 05:55
I've checked everything again - ROM is signed and that's confirmed by a ROM signature check app, there are no superuser binaries by default and I can even pass both device (integrated PIF) as well as strong (PIF & TrickyStore in KernelSU) with this ROM.

I'll close this. If the issue still persists, you may open the issue back.

**Closed by mytja** 2024-09-18 05:55 UTC

**Comment by Vad1mCSO2** [comment] 2024-10-03 03:41
https://youtu.be/N69yHbwN2Mo?si=61SEE1PI4HgxHWzx
